FoodAndCore/Controllers/FoodController.cs
using FoodAndCore.Data.Context;
using FoodAndCore.Data.Models;
using FoodAndCore.Repostories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using X.PagedList.Extensions;

namespace FoodAndCore.Controllers
{
    public class FoodController : Controller
    {
        Context db = new Context();
        FoodRepository foodRepository = new FoodRepository();
        public IActionResult Index(int page=1)
        {
            
            return View(foodRepository.GetList("Category").ToPagedList(page,5));
        }
        [HttpGet]
        public IActionResult AddFood()
        {
            List<SelectListItem> values = (from x in db.Categories.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.CategoryName,
                                               Value = x.CategoryID.ToString()
                                           }).ToList();

            ViewBag.vls = values;
            return View();
        }
        [HttpPost]
        public IActionResult AddFood(Food food)
        {
            foodRepository.TAdd(food);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult RemoveFood(int id) 
        {
            foodRepository.TRemove(new Food { FoodId = id });
            return RedirectToAction("Index");

        }

        public IActionResult GetFood(int id)
        {
            var x = foodRepository.GetT(id);
            List<SelectListItem> values = (from y in db.Categories.ToList()
                                           select new SelectListItem
                                           {
                                               Text = y.CategoryName,
                                               Value = y.CategoryID.ToString()
                                           }).ToList();

            ViewBag.vls = values;
            Food f = new Food() 
            {
                FoodId = x.FoodId,
                CategoryId=x.CategoryId,
                FoodName = x.FoodName,
                FoodDescription = x.FoodDescription,
                FoodPrice = x.FoodPrice,
                FoodStock = x.FoodStock,
                FoodImgUrl = x.FoodImgUrl,
            };
            return View(f);
        }
        [HttpPost]
        public IActionResult UpdateFood(Food f)
        {
            var x = foodRepository.GetT(f.FoodId);
            x.FoodName = f.FoodName;
            x.FoodDescription = f.FoodDescription;
            x.FoodPrice = f.FoodPrice;
            x.FoodImgUrl = f.FoodImgUrl;
            x.FoodStock = f.FoodStock;
            x.CategoryId = f.CategoryId;
            foodRepository.TUpdate(x);
            return RedirectToAction("Index");
        }
    }
}

FoodAndCore/Views/Food/AddFood.cshtml
@model FoodAndCore.Data.Models.Food
@{
	ViewData["Title"] = "AddFood";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>New Food</h1>
<br />
@using (Html.BeginForm("AddFood", "Food", FormMethod.Post))
{
	@Html.Label("Food Name:")
	@Html.TextBoxFor(x => x.FoodName, new { @class = "form-control" })
	<br />
	@Html.Label("Food Price:")
	@Html.TextBoxFor(x => x.FoodPrice, new { @class = "form-control" })
	<br />
	@Html.Label("Food IMG:")
	@Html.TextBoxFor(x => x.FoodImgUrl, new { @class = "form-control" })
	<br />
	@Html.Label("Food Stock:")
	@Html.TextBoxFor(x => x.FoodStock, new { @class = "form-control" })
	<br />
	@Html.Label("Food Category:")
	@Html.DropDownListFor(x => x.CategoryId, (List<SelectListItem>)ViewBag.vls, new { @class = "form-control" })
	<br />
	@Html.Label("Food Description:")
	@Html.TextAreaFor(x => x.FoodDescription, new { @class = "form-control" })
	<br />
	<button class="btn btn-success">Save</button>
}

FoodAndCore/Views/Food/GetFood.cshtml
@model FoodAndCore.Data.Models.Food
@{
    ViewData["Title"] = "GetFood";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Update Food</h1>
<br />
@using (Html.BeginForm("UpdateFood", "Food", FormMethod.Post))
{
	@Html.Label("Food ID:")
	@Html.TextBoxFor(x => x.FoodId, new { @class = "form-control" })
	<br />
	@Html.Label("Food Name:")
	@Html.TextBoxFor(x => x.FoodName, new { @class = "form-control" })
	<br />
	@Html.Label("Food Price:")
	@Html.TextBoxFor(x => x.FoodPrice, new { @class = "form-control" })
	<br />
	@Html.Label("Food IMG:")
	@Html.TextBoxFor(x => x.FoodImgUrl, new { @class = "form-control" })
	<br />
	@Html.Label("Food Stock:")
	@Html.TextBoxFor(x => x.FoodStock, new { @class = "form-control" })
	<br />
	@Html.Label("Food Category:")
	@Html.DropDownListFor(x => x.CategoryId, (List<SelectListItem>)ViewBag.vls, new { @class = "form-control" })
	<br />
	@Html.Label("Food Description:")
	@Html.TextAreaFor(x => x.FoodDescription, new { @class = "form-control" })
	<br />
	<button class="btn btn-success">Save</button>
}

FoodAndCore/Views/Food/Index.cshtml
@using X.PagedList;
@using X.PagedList.Mvc.Core;
@model IPagedList<FoodAndCore.Data.Models.Food>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Foods List</h1>
<br />
<table class="table table-brodered">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Price</th>
        <th>Image</th>
        <th>Stock</th>
        <th>Category</th>
        <th>Delete</th>
        <th>Update</th>
        <th>Details</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.FoodId</td>
            <td>@item.FoodName</td>
            <td>@item.FoodPrice TL</td>
            <td>@item.FoodImgUrl</td>
            <td>@item.FoodStock</td>
            <td>@item.Category.CategoryName</td>
            <td><a class="btn btn-danger" href="/Food/RemoveFood/@item.FoodId">Delete</a></td>
            <td><a class="btn btn-success" href="/Food/GetFood/@item.FoodId">Update</a></td>
            <td><a class="btn btn-warning">Details</a></td>
        </tr>
    }
</table>
@Html.PagedListPager((IPagedList)Model,page=>Url.Action("Index", new{page}))
<a class="btn btn-info" href="/Food/AddFood">New Food</a>